name: Formatter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requerements.txt
    - name: Formatting code with black
      run: |
        black src
    - name: Commiting changes
      run: |
        git config user.email "zgamesudio@gmail.com"
        git config user.name "Github actions"
        git add .
        git commit -m "Black format"
        git push
